apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-api
spec:
  selector:
    matchLabels:
      app: worker-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker-api
    spec:
      containers:
        - image: floresfrankd/worker-api:0.0.1
          name: worker-api
          env:
            # Use secret in real usage
            - name: MYSQLDB
              value: worker
            - name: MYSQLHOST
              value: mysql
            - name: MYSQLUSER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQLPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3000
              name: worker-api
          resources:
            requests:
              memory: "128Mi"
              cpu: "512m"
            limits:
              memory: "256Mi"
              cpu: "1024m"

---
apiVersion: v1
kind: Service
metadata:
  name: worker-api
spec:
  type: ClusterIP
  ports:
    - targetPort: 3000
      port: 3000
  selector:
    app: worker-api
